import { Flex, Text } from "@mantine/core";
import React from "react";

const NvtRights = () => {
  return (
    <Flex gap="lg" direction="column">
      <Text>6.1 NOVELT INC Rights.</Text>
      <Text>
        {`We reserve the right to take any action we deem necessary to prevent or remedy any violation
        or breach of the terms of this Agreement, including without limitation, terminating your
        access to the Services or your account or taking legal action against you. We may also
        terminate or suspend your access to the Services or your account at any time and without
        notice for any reason.`}
      </Text>
      <Text>
        {`DISCLAIMER OF WARRANTIES. THE SERVICES AND ALL CONTENT, INFORMATION, PRODUCTS, AND SERVICES
        INCLUDED IN OR AVAILABLE THROUGH THE SERVICES ARE PROVIDED "AS IS" AND "AS AVAILABLE" FOR
        YOUR USE. NOVELT INC DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED,
        INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR
        PURPOSE, TITLE, AND NON-INFRINGEMENT. NOVELT INC MAKES NO WARRANTY THAT (A) THE SERVICES OR
        ANY CONTENT, INFORMATION, PRODUCTS, OR SERVICES INCLUDED IN OR AVAILABLE THROUGH THE
        SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE, OR ERROR-FREE, (B) THE QUALITY OF ANY
        PRODUCTS, SERVICES, INFORMATION, OR OTHER MATERIAL PURCHASED OR OBTAINED BY YOU THROUGH THE
        SERVICES WILL MEET YOUR EXPECTATIONS, OR (C) ANY ERRORS IN THE SERVICES WILL BE CORRECTED.
        ANY MATERIAL DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE USE OF THE SERVICES IS DONE AT
        YOUR OWN DISCRETION AND RISK AND YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR
        COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIAL.`}
      </Text>
      <Text>
        {`LIMITATION OF LIABILITY. IN NO EVENT SHALL NOVELT INC OR ITS OFFICERS, DIRECTORS, EMPLOYEES,
        OR AGENTS BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY DAMAGES WHATSOEVER (INCLUDING, WITHOUT
        LIMITATION, INDIRECT, INCIDENTAL, SPECIAL, OR CONSEQUENTIAL DAMAGES, LOST PROFITS, OR
        DAMAGES RESULTING FROM LOST DATA OR BUSINESS INTERRUPTION) ARISING OUT OF OR IN CONNECTION
        WITH THE SERVICES`}
      </Text>
    </Flex>
  );
};

export default NvtRights;
